IniPec - RegistroImprese - Gateway
pagopa/pn-national-registries pull request #1
Opened 2022-12-21 09:17 UTC by SimoneMartelliNTTD

2023-01-09 09:48 UTC, MTurraPpa requested changes

2023-01-09 09:48 UTC, MTurraPpa commented on pom.xml
> +        <version>1.0.0</version>
Aggiornare alla 2.0.0-SNAPSHOT

2023-01-09 09:48 UTC, MTurraPpa commented on pom.xml
> +            <version>1.0.0</version>
Aggiornare alla 2.0.0-SNAPSHOT

2023-01-09 09:48 UTC, MTurraPpa commented on pn-national-registries.iml
>      <orderEntry type="inheritedJdk" />
Non committare file del IDE

2023-01-10 09:47 UTC, MTurraPpa requested changes
Rivedere i code smell segnalati da Sonar

2023-01-10 14:35 UTC, MTurraPpa reviewed
Come mai così tante versioni del file docs/openapi/PNT2Y-OpenAPI3_PN-NationalRegistries_vxxx.yaml?

2023-01-10 16:55 UTC, PlMuraNTT commented
> Come mai così tante versioni del file docs/openapi/PNT2Y-OpenAPI3_PN-NationalRegistries_vxxx.yaml?

Hanno la funzione di storico, se ritieni che sia eccessiva come cosa lasciamo solo l'ultima versione

2023-01-10 17:06 UTC, vincenzo-racca-pa approved these changes

2023-01-11 13:55 UTC, MTurraPpa requested changes
Verificare i code smell https://sonarcloud.io/project/issues?id=pagopa_pn-national-registries&pullRequest=1&resolved=false&types=CODE_SMELL

2023-01-11 14:45 UTC, PlMuraNTT approved these changes

2023-01-11 14:51 UTC, PlMuraNTT approved these changes

2023-01-11 14:51 UTC, PlMuraNTT approved these changes

2023-01-11 14:52 UTC, PlMuraNTT approved these changes

2023-01-11 14:53 UTC, PlMuraNTT approved these changes

2023-01-11 14:57 UTC, PlMuraNTT approved these changes
Review eseguita

2023-01-11 16:03 UTC, MTurraPpa approved these changes

2023-01-16 10:59 UTC, PlMuraNTT commented on scripts/aws/cfn/storage.yml
> +        - AttributeName: "cf"
Risolvo per sbloccare rilascio in test, da riaprire alla prossima PR

2023-01-16 10:59 UTC, merged